/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.tomcat.jni.Library;
import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Ignore
    @Test public void testSomeLibraryMethod() {
    //    Library classUnderTest = new Library();
    //    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
